# Generated by Django 5.1.7 on 2025-05-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MainProduct',
        ),
        migrations.DeleteModel(
            name='TopProduct',
        ),
    ]
