# Generated by Django 5.1.7 on 2025-05-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cartitem_count_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
