# Generated by Django 5.1.7 on 2025-04-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(default=18)),
                ('email', models.EmailField(default=255, max_length=254, unique=True)),
                ('fav_toy', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
