# Generated by Django 5.1.7 on 2025-04-16 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='myapp.group'),
        ),
        migrations.AlterField(
            model_name='librarycard',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
    ]
