# Generated by Django 5.1.7 on 2025-04-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
